//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MENSAGEM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MENSAGEM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SW.Resources.MENSAGEM", typeof(MENSAGEM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do produto &quot;.
        /// </summary>
        public static string CONFIRMACAO_EXCLUSAO_PRODUTO {
            get {
                return ResourceManager.GetString("CONFIRMACAO_EXCLUSAO_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão da promoção &quot;.
        /// </summary>
        public static string CONFIRMACAO_EXCLUSAO_PROMOCAO {
            get {
                return ResourceManager.GetString("CONFIRMACAO_EXCLUSAO_PROMOCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um produto cadastrado com o nome informado. Informe outro nome..
        /// </summary>
        public static string ERRO_PRODUTO_NOME_DUPLICADO {
            get {
                return ResourceManager.GetString("ERRO_PRODUTO_NOME_DUPLICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço do produto deve ser maior que 0..
        /// </summary>
        public static string ERRO_PRODUTO_VALOR_ZERADO {
            get {
                return ResourceManager.GetString("ERRO_PRODUTO_VALOR_ZERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uma promoção cadastrada com o nome informado. Informe outro nome..
        /// </summary>
        public static string ERRO_PROMOCAO_NOME_DUPLICADO {
            get {
                return ResourceManager.GetString("ERRO_PROMOCAO_NOME_DUPLICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de  produtos deve ser maior que 0..
        /// </summary>
        public static string ERRO_PROMOCAO_QUANTIDADE_PRODUTOS_ZERADO {
            get {
                return ResourceManager.GetString("ERRO_PROMOCAO_QUANTIDADE_PRODUTOS_ZERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para o tipo de cobrança &quot;ValorFixo&quot; o valor fixo deve ser maior que 0..
        /// </summary>
        public static string ERRO_PROMOCAO_VALOR_FIXO_ZERADO {
            get {
                return ResourceManager.GetString("ERRO_PROMOCAO_VALOR_FIXO_ZERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; é obrigatório e não foi informado..
        /// </summary>
        public static string ERRO_VALIDACAO_CAMPO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERRO_VALIDACAO_CAMPO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do campo foi excedido..
        /// </summary>
        public static string ERRO_VALIDACAO_TAMANHO_MAXIMO_EXCEDIDO {
            get {
                return ResourceManager.GetString("ERRO_VALIDACAO_TAMANHO_MAXIMO_EXCEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto excluído com sucesso..
        /// </summary>
        public static string PRODUTO_EXCLUIDO_SUCESSO {
            get {
                return ResourceManager.GetString("PRODUTO_EXCLUIDO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto incluído com sucesso..
        /// </summary>
        public static string PRODUTO_INCLUIDO_SUCESSO {
            get {
                return ResourceManager.GetString("PRODUTO_INCLUIDO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoção excluída com sucesso..
        /// </summary>
        public static string PROMOCAO_EXCLUIDO_SUCESSO {
            get {
                return ResourceManager.GetString("PROMOCAO_EXCLUIDO_SUCESSO", resourceCulture);
            }
        }
    }
}
