//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PROPRIEDADE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PROPRIEDADE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SW.Resources.PROPRIEDADE", typeof(PROPRIEDADE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ITEM {
            get {
                return ResourceManager.GetString("ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string NOME {
            get {
                return ResourceManager.GetString("NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        public static string PRECO {
            get {
                return ResourceManager.GetString("PRECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoção.
        /// </summary>
        public static string PROMOCAO {
            get {
                return ResourceManager.GetString("PROMOCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoção ativa.
        /// </summary>
        public static string PROMOCAO_ATIVA {
            get {
                return ResourceManager.GetString("PROMOCAO_ATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string QUANTIDADE {
            get {
                return ResourceManager.GetString("QUANTIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de produtos.
        /// </summary>
        public static string QUANTIDADE_PRODUTOS {
            get {
                return ResourceManager.GetString("QUANTIDADE_PRODUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de cobrança.
        /// </summary>
        public static string TIPO_COBRANCA {
            get {
                return ResourceManager.GetString("TIPO_COBRANCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor fixo.
        /// </summary>
        public static string VALOR_FIXO {
            get {
                return ResourceManager.GetString("VALOR_FIXO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total.
        /// </summary>
        public static string VALOR_TOTAL {
            get {
                return ResourceManager.GetString("VALOR_TOTAL", resourceCulture);
            }
        }
    }
}
