// <auto-generated />
namespace SW.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class valor_fixo_promocao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(valor_fixo_promocao));
        
        string IMigrationMetadata.Id
        {
            get { return "201504060214175_valor_fixo_promocao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
